************* Module ../pyanaconda/anaconda.py
/usr/lib/python3.5/site-packages/astroid/bases.py:302: PyGIWarning: BlockDev was imported without specifying a version first. Use gi.require_version('BlockDev', '1.0') before import to ensure that the right version gets loaded.
  for res in _func(node, context, **kwargs):
************* Module ../anaconda.py
/usr/lib/python3.5/site-packages/astroid/bases.py:302: PyGIWarning: BlockDev was imported without specifying a version first. Use gi.require_version('BlockDev', '1.0') before import to ensure that the right version gets loaded.
  for res in _func(node, context, **kwargs):
************* Module ../pyanaconda/ui/gui/spokes/network.py
/usr/lib/python3.5/site-packages/astroid/bases.py:302: PyGIWarning: NM was imported without specifying a version first. Use gi.require_version('NM', '1.0') before import to ensure that the right version gets loaded.
  for res in _func(node, context, **kwargs):
************* Module ../pyanaconda/ui/gui/spokes/lib/accordion.py
/usr/lib/python3.5/site-packages/astroid/context.py:49: PyGIWarning: AnacondaWidgets was imported without specifying a version first. Use gi.require_version('AnacondaWidgets', '3.3') before import to ensure that the right version gets loaded.
  for result in generator:
************* Unused False Positives Found:
^E0611.*: No name '_isys' in module 'pyanaconda'$
PASS pylint/runpylint.py (exit status: 0)
