************* Unused False Positives Found:
^E0611.*: No name '_isys' in module 'pyanaconda'$
PASS pylint/runpylint.py (exit status: 0)
